### ISSUE TITLE
This extension is further developed

### ISSUE THREAD

**Issue by ghost** [alifaraji/randomtopics#1]
Hello Developers,

I discovered your "Random Topics" extension and installed it under PHPBB 3.2.0. In the frontend of my forum everything is displayed normally and I put the Random Topics on 3 topics to be displayed.

Will you consider this extension with regard to PHPBB 3.2 again more detailed or will it only remain with PHPBB 3.1.

Would be interesting, if the development continues.

Thanks in advance.

**Comment by alifaraji** [comment]
Hello

Random Topics extension is now compatible with phpBB 3.3

Thanks
